# old build file for Travis CI
dist: bionic

language: java

os:
  - linux

git:
  depth: 2

cache:
  directories:
  - $HOME/.m2/bin
  - $HOME/.m2/repository
  - $HOME/.xshare
before_cache:
  - rm -rf $HOME/.m2/repository/com/vegardit

jdk:
  - openjdk8 # used by maven runtime

install:
  - printenv | sort
  - which java
  - echo JAVA_HOME=$JAVA_HOME
  - ls -l /usr/lib/jvm/
  - ls -l /usr/local/lib/jvm/
  - ls -l $HOME/.m2

before_script:
  - unset _JAVA_OPTIONS # https://github.com/travis-ci/travis-ci/issues/8408

script:
  - bash .ci/build.sh
